allow-lan: true
dns:
  enable: true
  fallback:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - tls://1.0.0.1:853
  - tls://dns.google:853
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
external-controller: :9090
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: aes-256-gcm
  name: 美国
  password: 7ae4e68cf77f6089
  port: 40129
  server: 46.17.41.202
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 新加坡
  password: rlnuK3GkwkfM
  port: 8388
  server: 192.124.176.49
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 日本
  password: ngwyAZszOE90
  port: 8388
  server: 185.141.219.93
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 香港
  password: rjb2277Yf9nu
  port: 8388
  server: 212.192.12.81
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 台湾
  password: c5fcdf7829112cb4
  port: 60129
  server: 45.140.169.216
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 法国
  password: 3150466568eda87b
  port: 60129
  server: 195.58.49.26
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 泰国
  password: 1a87017d0bf57f34
  port: 60129
  server: 176.32.39.99
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 澳大利亚
  password: 1a87017d0bf57f34
  port: 60129
  server: 176.32.39.99
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 加拿大
  password: 9f3d1a6d31468599
  port: 60129
  server: 195.58.49.9
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 韩国
  password: 63d7c17506d1f48b
  port: 60981
  server: 203.32.26.24
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 英国
  password: f34579d0148b2581
  port: 9012
  server: 185.22.154.104
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 西班牙
  password: f34579d0148b2581
  port: 9012
  server: 185.22.154.104
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 香港2
  password: 7e1dd4c55bf85da5
  port: 40210
  server: 212.192.15.78
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 俄罗斯
  password: 9ca2803c16de72cd
  port: 60129
  server: 46.17.41.191
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 日本2
  password: 99394cfebe6c0906
  port: 30312
  server: 185.141.219.21
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 法国2
  password: 9ca2803c16de72cd
  port: 60129
  server: 46.17.41.191
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: JPOsaka
  password: dada1203
  port: 80
  server: 54.169.99.200
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: JPTokyo
  password: dada1203
  port: 80
  server: 13.212.90.94
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: USHouston
  password: dada1203
  port: 80
  server: 52.33.188.199
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: TWTaipei
  password: dada1203
  port: 80
  server: 54.179.165.29
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: SGSingapore
  password: dada1203
  port: 80
  server: 54.255.183.1
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: CAVancouver
  password: dada1203
  port: 80
  server: 44.249.55.56
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: KRIncheon
  password: dada1203
  port: 80
  server: 13.229.216.50
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: USCalifornia
  password: dada1203
  port: 80
  server: 98.84.171.117
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线5线
  password: hahrgnUUr991
  port: 48209
  server: 182.61.60.225
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线1线
  password: tiuuxUi0897
  port: 40237
  server: 8.134.98.238
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线8线
  password: hahrgnUUr991
  port: 48209
  server: 182.61.60.225
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线7线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线2线
  password: tiuuxUi0897
  port: 40237
  server: 8.134.98.238
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线4线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线3线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线6线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: Chicago#101
  password: QTmLViU4VEmuwbOxUw4IXd
  port: 59556
  server: 107.172.250.161
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: Germany#101
  password: SUSbr2eLCXmbc64xOHhgEt
  port: 41195
  server: 167.172.249.115
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: Germany#102
  password: Q7cjiVD0oKNE2o9sUnZKQg
  port: 23243
  server: 46.101.196.138
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: London#101
  password: idMvoewrSyLLvEvP03k9zR
  port: 46576
  server: 138.68.153.223
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: Netherlands
  password: WC0GbiCk67K8nHDaDHmYIX
  port: 19582
  server: 159.223.236.36
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: New Jersey
  password: ExUzHZ3AqMIVRmz9r6mcgy
  port: 19353
  server: 66.154.114.231
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: New York#101
  password: elTuo73FsQwO90EbLo96Ve
  port: 49726
  server: 45.55.40.127
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: New York#105
  password: 5vldsNMbQ8B4cKDK0sROwj
  port: 20683
  server: 142.93.183.235
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: New York#106
  password: hk1SdyRWbYi3Igxeow9JdN
  port: 45389
  server: 142.93.73.182
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: New York#107
  password: DZRy4Q3QH0jUGfKFl2jDCZ
  port: 28960
  server: 138.197.89.234
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: USA#1
  password: hk1SdyRWbYi3Igxeow9JdN
  port: 45389
  server: 142.93.73.182
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: Bangalore (Auto)
  password: XFxsnx65klydzrAAEeEcgJWpmK0XGDyV7usnRVCWvhc
  port: 8388
  server: 168.144.66.248
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: Singapore (Auto)
  password: 7GaQIM4q84sLnhqQJ8mLqb0KbdDmBWxKPaXa59tFXtg
  port: 8388
  server: 165.22.111.31
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: Sydney#1
  password: DOvMXAYGG7u4gb68FIYQCSfLebq1BOjBwz09jnjmWQ
  port: 8388
  server: 134.199.149.225
  type: ss
  udp: true
proxy-groups:
- name: 🚀 SS节点选择
  proxies:
  - 美国
  - 新加坡
  - 日本
  - 香港
  - 台湾
  - 法国
  - 泰国
  - 澳大利亚
  - 加拿大
  - 韩国
  - 英国
  - 西班牙
  - 香港2
  - 俄罗斯
  - 日本2
  - 法国2
  - JPOsaka
  - JPTokyo
  - USHouston
  - TWTaipei
  - SGSingapore
  - CAVancouver
  - KRIncheon
  - USCalifornia
  - 高速专线5线
  - 高速专线1线
  - 高速专线8线
  - 高速专线7线
  - 高速专线2线
  - 高速专线4线
  - 高速专线3线
  - 高速专线6线
  - Chicago#101
  - Germany#101
  - Germany#102
  - London#101
  - Netherlands
  - New Jersey
  - New York#101
  - New York#105
  - New York#106
  - New York#107
  - USA#1
  - Bangalore (Auto)
  - Singapore (Auto)
  - Sydney#1
  - DIRECT
  type: select
rules:
- GEOIP,CN,DIRECT
- MATCH,🚀 SS节点选择
socks-port: 7891
