allow-lan: true
dns:
  enable: true
  fallback:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - tls://1.0.0.1:853
  - tls://dns.google:853
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
external-controller: :9090
log-level: info
mode: Rule
port: 7890
proxies:
- cipher: aes-256-gcm
  name: 美国
  password: 32c0ea6e823341a2
  port: 32324
  server: 46.29.163.30
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 新加坡
  password: hxoxVYlGXJDq
  port: 8388
  server: 194.87.10.155
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 日本
  password: AKwE7SVMLTjC
  port: 8388
  server: 185.141.219.215
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 香港
  password: ItBgVHOiVpEy
  port: 8388
  server: 212.192.12.242
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 台湾
  password: c5fcdf7829112cb4
  port: 24213
  server: 46.29.163.104
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 法国
  password: fbaf33bcffe53cf9
  port: 23242
  server: 176.32.39.96
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 泰国
  password: 1a87017d0bf57f34
  port: 32432
  server: 195.58.48.56
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 澳大利亚
  password: 1a87017d0bf57f34
  port: 32432
  server: 195.58.48.56
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 加拿大
  password: 9f3d1a6d31468599
  port: 60129
  server: 176.32.39.72
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 意大利
  password: cfe685726eea2c4b
  port: 50129
  server: 46.17.43.28
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 英国
  password: cfe685726eea2c4b
  port: 50129
  server: 46.17.43.28
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 西班牙
  password: 7e1dd4c55bf85da5
  port: 30129
  server: 103.136.150.192
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 香港2
  password: b24a80e79cee1d1f
  port: 20129
  server: 46.29.163.195
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 俄罗斯
  password: 2803361d6c196af8
  port: 60129
  server: 166.1.228.207
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 加拿大2
  password: b24a80e79cee1d1f
  port: 20129
  server: 46.29.163.195
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: KRIncheon
  password: dada1203
  port: 80
  server: 52.77.218.174
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: SGSingapore
  password: dada1203
  port: 80
  server: 13.212.100.119
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: JPOsaka
  password: dada1203
  port: 80
  server: 13.212.19.216
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: CAVancouver
  password: dada1203
  port: 80
  server: 18.227.24.125
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: USHouston
  password: dada1203
  port: 80
  server: 3.146.178.252
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: JPTokyo
  password: dada1203
  port: 80
  server: 54.151.199.29
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: TWTaipei
  password: dada1203
  port: 80
  server: 47.128.149.14
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: USCalifornia
  password: dada1203
  port: 80
  server: 18.224.64.232
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线8线
  password: hahrgnUUr991
  port: 48209
  server: 182.61.60.225
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线3线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线6线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线2线
  password: tiuuxUi0897
  port: 40237
  server: 8.134.98.238
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线1线
  password: tiuuxUi0897
  port: 40237
  server: 8.134.98.238
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线5线
  password: hahrgnUUr991
  port: 48209
  server: 182.61.60.225
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线7线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 高速专线4线
  password: OlpwJ465
  port: 30238
  server: 125.122.25.163
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: California#101
  password: BXGEJN9uWJIklXht5PWQHW
  port: 34078
  server: 67.216.201.132
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: Chicago#101
  password: QTmLViU4VEmuwbOxUw4IXd
  port: 59556
  server: 107.172.250.161
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: Germany#102
  password: Q7cjiVD0oKNE2o9sUnZKQg
  port: 23243
  server: 46.101.196.138
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: London#101
  password: idMvoewrSyLLvEvP03k9zR
  port: 46576
  server: 138.68.153.223
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: New York#107
  password: DZRy4Q3QH0jUGfKFl2jDCZ
  port: 28960
  server: 138.197.89.234
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: USA#1
  password: hk1SdyRWbYi3Igxeow9JdN
  port: 45389
  server: 142.93.73.182
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: USA-New Jersey
  password: 66SHCeHGxhnRonfCoRtisf
  port: 50469
  server: 66.154.114.231
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: Amsterdam#1
  password: R8EJfhdHzSUYeicBMZYp58ctYYzDqDO3LEqXYj6PnM
  port: 8388
  server: 146.190.236.203
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: Bangalore (Auto)
  password: XFxsnx65klydzrAAEeEcgJWpmK0XGDyV7usnRVCWvhc
  port: 8388
  server: 168.144.66.248
  type: ss
  udp: true
proxy-groups:
- name: 🚀 SS节点选择
  proxies:
  - 美国
  - 新加坡
  - 日本
  - 香港
  - 台湾
  - 法国
  - 泰国
  - 澳大利亚
  - 加拿大
  - 意大利
  - 英国
  - 西班牙
  - 香港2
  - 俄罗斯
  - 加拿大2
  - KRIncheon
  - SGSingapore
  - JPOsaka
  - CAVancouver
  - USHouston
  - JPTokyo
  - TWTaipei
  - USCalifornia
  - 高速专线8线
  - 高速专线3线
  - 高速专线6线
  - 高速专线2线
  - 高速专线1线
  - 高速专线5线
  - 高速专线7线
  - 高速专线4线
  - California#101
  - Chicago#101
  - Germany#102
  - London#101
  - New York#107
  - USA#1
  - USA-New Jersey
  - Amsterdam#1
  - Bangalore (Auto)
  - DIRECT
  type: select
rules:
- GEOIP,CN,DIRECT
- MATCH,🚀 SS节点选择
socks-port: 7891
